import type { RagArtifactsResponse, RagStatusResponse } from "../types.js";

const artifactPaths = {
  requestSchema: "shared/schemas/rag-governance/rag-request.schema.json",
  responseSchema: "shared/schemas/rag-governance/rag-response.schema.json",
  chunkExport: "examples/rag-pattern/python/sample_outputs/cloudai-rag-chunks.json",
  evalDataset: "examples/rag-pattern/python/sample_outputs/cloudai-rag-eval-dataset.json",
  scoreReport: "examples/rag-pattern/python/sample_outputs/cloudai-rag-score-report.json",
  walkthrough: "examples/rag-pattern/python/DEMO_WALKTHROUGH.md"
} as const;

export function getRagStatus(): RagStatusResponse {
  return {
    status: "available",
    mode: "mock",
    workflow: "local-rag-governance",
    summary: "Local metadata endpoint for the synthetic RAG governance workflow and sample artifacts.",
    artifacts: artifactPaths,
    boundaries: {
      embeddings: false,
      vectorIndex: false,
      modelCalls: false,
      cloudDeployment: false,
      pythonExecutionFromApi: false
    }
  };
}

export function getRagArtifacts(): RagArtifactsResponse {
  return {
    mode: "mock",
    workflow: "local-rag-governance",
    artifacts: [
      {
        name: "RAG request contract",
        kind: "schema",
        path: artifactPaths.requestSchema,
        description: "Documents the governed RAG request shape used by synthetic examples."
      },
      {
        name: "RAG response contract",
        kind: "schema",
        path: artifactPaths.responseSchema,
        description: "Documents governed RAG responses, citations, retrieval metadata, and egress decisions."
      },
      {
        name: "Chunk export sample",
        kind: "sample-output",
        path: artifactPaths.chunkExport,
        description: "Sample chunk output generated by the local Python ingest workflow."
      },
      {
        name: "Eval dataset sample",
        kind: "sample-output",
        path: artifactPaths.evalDataset,
        description: "Sample question-and-answer dataset for local RAG quality checks."
      },
      {
        name: "Score report sample",
        kind: "sample-output",
        path: artifactPaths.scoreReport,
        description: "Sample local quality scoring report for mock RAG responses."
      },
      {
        name: "RAG walkthrough",
        kind: "documentation",
        path: artifactPaths.walkthrough,
        description: "Step-by-step local walkthrough for the mock RAG governance workflow."
      }
    ]
  };
}
