grafana:
  service:
    type: ClusterIP
  persistence:
    enabled: false
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL

prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    retention: 6h
    storageSpec: {}
